<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-04 22:05:24                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class ProtoSecurityLog extends AutoProtoSecurityLog {/*_*/}
?>