<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-05 14:55:03                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class ProtoAclGroupRight extends AutoProtoAclGroupRight {/*_*/}
?>