<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-12 23:19:36                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class ProtoCreditRequest extends AutoProtoCreditRequest {/*_*/}
?>