<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-06-23 13:22:32                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class ProtoNews extends AutoProtoNews {/*_*/}
?>