<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-04 15:15:32                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoActionLog extends AutoProtoActionLog {/*_*/}
?>