<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-08 18:33:13                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCreditorDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'creditor';
		}
		
		public function getObjectName()
		{
			return 'Creditor';
		}
		
		public function getSequence()
		{
			return 'creditor_id';
		}
	}
?>