<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-04 15:27:14                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoAclActionEditedDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'acl_action';
		}
		
		public function getObjectName()
		{
			return 'AclActionEdited';
		}
		
		public function getSequence()
		{
			return 'acl_action_id';
		}
	}
?>