<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-04 21:59:12                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoAuthLogDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'auth_log';
		}
		
		public function getObjectName()
		{
			return 'AuthLog';
		}
		
		public function getSequence()
		{
			return 'auth_log_id';
		}
	}
?>