<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-04 14:40:34                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoInvestorOfferDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'investor_offer';
		}
		
		public function getObjectName()
		{
			return 'InvestorOffer';
		}
		
		public function getSequence()
		{
			return 'investor_offer_id';
		}
	}
?>