<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-04 15:15:32                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoActionLogDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'action_log';
		}
		
		public function getObjectName()
		{
			return 'ActionLog';
		}
		
		public function getSequence()
		{
			return 'action_log_id';
		}
	}
?>