<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-02-17 01:39:32                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCreditRequestCreditorOfferDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'credit_request_creditor_offer';
		}
		
		public function getObjectName()
		{
			return 'CreditRequestCreditorOffer';
		}
		
		public function getSequence()
		{
			return 'credit_request_creditor_offer_id';
		}
	}
?>