<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-02-08 01:10:03                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCreditRequestImageDAO extends ImageBaseDAO
	{
		public function getTable()
		{
			return 'credit_request_image';
		}
		
		public function getObjectName()
		{
			return 'CreditRequestImage';
		}
		
		public function getSequence()
		{
			return 'credit_request_image_id';
		}
	}
?>