<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-02-25 12:53:22                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCreditRequestCreditorInvestorOfferDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'credit_request_creditor_investor_offer';
		}
		
		public function getObjectName()
		{
			return 'CreditRequestCreditorInvestorOffer';
		}
		
		public function getSequence()
		{
			return 'credit_request_creditor_investor_offer_id';
		}
	}
?>