<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2019-12-29 02:09:44                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoConfirmDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'confirm';
		}
		
		public function getObjectName()
		{
			return 'Confirm';
		}
		
		public function getSequence()
		{
			return 'confirm_id';
		}
	}
?>