<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-02-11 03:06:09                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCreditRequestCreditorDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'credit_request_creditor';
		}
		
		public function getObjectName()
		{
			return 'CreditRequestCreditor';
		}
		
		public function getSequence()
		{
			return 'credit_request_creditor_id';
		}
	}
?>