<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-04 15:34:44                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class AclContextDAO extends AutoAclContextDAO
	{
            const UQ_ACL_CONTEXT = 'uq_acl_context';
	}
?>