<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-05 14:55:03                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class AclGroupRightsDAO extends OneToManyLinked
	{
		public function __construct(AclGroup $aclGroup, $lazy = false)
		{
			parent::__construct(
				$aclGroup,
				AclGroupRight::dao(),
				$lazy
			);
		}
		
		/**
		 * @return AclGroupRightsDAO
		**/
		public static function create(AclGroup $aclGroup, $lazy = false)
		{
			return new self($aclGroup, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'group_id';
		}
	}
?>