<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-04 21:59:12                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class AuthLogDAO extends AutoAuthLogDAO
	{
            /**
             * @param Identifier $object
             * @return AuthLog
             */
            public function add(Identifiable $object)
            {
                return parent::add($object->setCreatedTime(Timestamp::makeNow()));
            }
	}
?>