<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2019-12-29 02:09:44                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class ConfirmDAO extends AutoConfirmDAO
	{
            const UQ_CONFIRM_CODE = 'uq_confirm_code';
            const UQ_CONFIRM_TYPE = 'uq_confirm_type';

            public function add(Identifiable $confirm)
            {
                if (!$confirm->getCreatedTime() instanceof Timestamp) {
                    $confirm->setCreatedTime(Timestamp::makeNow());
                }
                
                if (!$confirm->getExpiredTime() instanceof Timestamp) {
                    if ($confirm->getType()->getId() == ConfirmType::TYPE_REGISTRATION_PHONE) {
                        $confirm->setExpiredTime(Timestamp::makeNow()->modify("+20 minute"));
                    } elseif ($confirm->getType()->getId() == ConfirmType::TYPE_RECOVERY_EMAIL) {
                        $confirm->setExpiredTime(Timestamp::makeNow()->modify("+40 minute"));
                    } elseif ($confirm->getType()->getId() == ConfirmType::TYPE_RECOVERY_PHONE) {
                        $confirm->setExpiredTime(Timestamp::makeNow()->modify("+20 minute"));
                    } elseif ($confirm->getType()->getId() == ConfirmType::TYPE_CREDIT_REQUEST) {
                        $confirm->setExpiredTime(Timestamp::create("+20 minute"));
                    } elseif ($confirm->getType()->getId() == ConfirmType::TYPE_TELEGRAM_LINK) {
                        $confirm->setExpiredTime(Timestamp::create("+20 minute"));
                    }
                }

                return parent::add($confirm);
            }
	}
?>