<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-02-17 01:39:32                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class CreditRequestCreditorOfferDAO extends AutoCreditRequestCreditorOfferDAO
	{
            /**
             * @param Identifiable $user
             * @return CreditRequestCreditorOffer
             */
            public function add(Identifiable $creditRequestCreditorOffer)
            {
                if (!$creditRequestCreditorOffer->getCreatedTime() instanceof Timestamp) {
                    $creditRequestCreditorOffer->setCreatedTime(Timestamp::makeNow());
                }
                
                if (!$creditRequestCreditorOffer->getStatus() instanceof CreditRequestCreditorOfferStatus) {
                    $creditRequestCreditorOffer->setStatusId(CreditRequestCreditorOfferStatus::TYPE_INCOME);
                }

                return parent::add($creditRequestCreditorOffer);
            }
            
            public function income(CreditRequestCreditorOffer $creditRequestCreditorOffer)
            {
                return $this->save($creditRequestCreditorOffer->setStatusId(CreditRequestCreditorOfferStatus::TYPE_INCOME));
            }
            
            public function accept(CreditRequestCreditorOffer $creditRequestCreditorOffer)
            {
                return $this->save($creditRequestCreditorOffer->setStatusId(CreditRequestCreditorOfferStatus::TYPE_ACCEPTED));
            }
            
            public function reject(CreditRequestCreditorOffer $creditRequestCreditorOffer)
            {
                return $this->save($creditRequestCreditorOffer->setStatusId(CreditRequestCreditorOfferStatus::TYPE_REJECT));
            }
            
            public function cancel(CreditRequestCreditorOffer $creditRequestCreditorOffer)
            {
                return $this->save($creditRequestCreditorOffer->setStatusId(CreditRequestCreditorOfferStatus::TYPE_CANCELED));
            }
	}
?>