<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-02-11 03:06:09                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class CreditRequestCreditorDAO extends AutoCreditRequestCreditorDAO
	{
            /**
             * @param Identifiable $user
             * @return CreditRequestCreditor
             */
            public function add(Identifiable $creditRequestCreditor)
            {
                if (!$creditRequestCreditor->getCreatedTime() instanceof Timestamp) {
                    $creditRequestCreditor->setCreatedTime(Timestamp::makeNow());
                }

                return parent::add($creditRequestCreditor);
            }
	}
?>