<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-12 23:19:36                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class CreditRequestDAO extends AutoCreditRequestDAO
	{
            /**
             * @param Identifiable $user
             * @return CreditRequest
             */
            public function add(Identifiable $creditRequest)
            {
                if (!$creditRequest->getCreatedTime() instanceof Timestamp) {
                    $creditRequest->setCreatedTime(Timestamp::makeNow());
                }
                
                if (!$creditRequest->getStatus() instanceof CreditRequestStatus) {
                    $creditRequest->setStatus(CreditRequestStatus::create(CreditRequestStatus::TYPE_INCOME));
                }

                return parent::add($creditRequest);
            }
            
            public function markAsDeleted(CreditRequest $creditRequest)
            {
                return $this->save($creditRequest->setDeleted(true));
            }
            
            public function restore(CreditRequest $creditRequest)
            {
                return $this->save($creditRequest->setDeleted(false));
            }
	}
?>