<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-02-25 12:53:22                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class CreditRequestCreditorInvestorOfferDAO extends AutoCreditRequestCreditorInvestorOfferDAO
	{
		// last chance for customization
	}
?>