<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-02-17 01:40:44                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class CreditRequestCreditorOffersDAO extends OneToManyLinked
	{
		public function __construct(CreditRequestCreditor $creditRequestCreditor, $lazy = false)
		{
			parent::__construct(
				$creditRequestCreditor,
				CreditRequestCreditorOffer::dao(),
				$lazy
			);
		}
		
		/**
		 * @return CreditRequestCreditorOffersDAO
		**/
		public static function create(CreditRequestCreditor $creditRequestCreditor, $lazy = false)
		{
			return new self($creditRequestCreditor, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'request_id';
		}
	}
?>