<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-02-08 01:10:03                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class CreditRequestImageDAO extends AutoCreditRequestImageDAO
	{
		// your brilliant stuff goes here
	}
?>