<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2019-12-26 13:56:19                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class ImageOwnerImagesDAO extends OneToManyLinked
	{
		public function __construct(ImageOwner $imageOwner, $lazy = false)
		{
			parent::__construct(
				$imageOwner,
				ImageBase::dao(),
				$lazy
			);
		}
		
		/**
		 * @return ImageOwnerImagesDAO
		**/
		public static function create(ImageOwner $imageOwner, $lazy = false)
		{
			return new self($imageOwner, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'image_owner_id';
		}
	}
?>