<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2019-12-26 13:56:19                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	abstract class ImageOwnerDAO extends AutoImageOwnerDAO
	{
            public function dropById($id)
            {
                try {
                    $tr = InnerTransaction::begin($this);

                    $object = $this->getById($id);
                    if ($object->getImages(true)->getList()) {
                        $object->getImages(true)->getDao()->dropByIds(
                            $object->getImages(true)->getList()
                        );
                    }

                    $count = parent::dropById($id);

                    $tr->commit();
                } catch (Exception $e) {
                    $tr->rollback();

                    throw $e;
                }

                return $count;
            }

            public function dropByIds(array $ids)
            {
                try {
                    $tr = InnerTransaction::begin($this);

                    foreach($ids as $id) {
                        $object = $this->getById($id);
                        if ($object->getImages(true)->getList()) {
                            $object->getImages(true)->getDao()->dropByIds(
                                $object->getImages(true)->getList()
                            );
                        }
                    }

                    $count = parent::dropByIds($ids);

                    $tr->commit();
                } catch (Exception $e) {
                    $tr->rollback();

                    throw $e;
                }

                return $count;
            }
	}
?>