<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-04 14:40:34                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class InvestorOfferDAO extends AutoInvestorOfferDAO
	{
            public function add(Identifiable $confirm)
            {
                if (!$confirm->getCreatedTime() instanceof Timestamp) {
                    $confirm->setCreatedTime(Timestamp::makeNow());
                }

                return parent::add($confirm);
            }
            
            public function markAsDeleted(InvestorOffer $offer)
            {
                return $this->save($offer->setDeleted(true));
            }
            
            public function restore(InvestorOffer $offer)
            {
                return $this->save($offer->setDeleted(false));
            }
	}
?>