<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2019-12-26 13:54:24                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class UserDAO extends AutoUserDAO
	{
            //const UQ_CONFIRM_CODE = 'uq_confirm_code';

            public function add(Identifiable $user)
            {
                if (!$user->getCreatedTime() instanceof Timestamp) {
                    $user->setCreatedTime(Timestamp::makeNow());
                }

                return parent::add($user);
            }
	}
?>