<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-04 21:50:15                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class UserClonesDAO extends ManyToManyLinked
	{
		public function __construct(User $user, $lazy = false)
		{
			parent::__construct(
				$user,
				User::dao(),
				$lazy
			);
		}
		
		/**
		 * @return UserClonesDAO
		**/
		public static function create(User $user, $lazy = false)
		{
			return new self($user, $lazy);
		}
		
		public function getHelperTable()
		{
			return 'user_clones';
		}
		
		public function getChildIdField()
		{
			return 'clone_id';
		}
		
		public function getParentIdField()
		{
			return 'user_id';
		}
	}
?>