<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-05 14:55:03                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoAclGroupRight extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'AclGroupRight', 8, true, true, false, null, null),
				'right' => LightMetaProperty::fill(new LightMetaProperty(), 'right', 'right_id', 'integerIdentifier', 'AclRight', null, true, false, false, 1, 3),
				'group' => LightMetaProperty::fill(new LightMetaProperty(), 'group', 'group_id', 'integerIdentifier', 'AclGroup', null, true, false, false, 1, 3)
			);
		}
	}
?>