<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-05 01:54:35                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoAuthLog extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'AuthLog', 8, true, true, false, null, null),
				'createdTime' => LightMetaProperty::fill(new LightMetaProperty(), 'createdTime', 'created_time', 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'user' => LightMetaProperty::fill(new LightMetaProperty(), 'user', 'user_id', 'identifier', 'User', null, false, false, false, 1, 3),
				'login' => LightMetaProperty::fill(new LightMetaProperty(), 'login', null, 'string', null, 128, false, true, false, null, null),
				'sid' => LightMetaProperty::fill(new LightMetaProperty(), 'sid', null, 'string', null, 64, false, true, false, null, null),
				'ip' => LightMetaProperty::fill(new LightMetaProperty(), 'ip', null, 'integer', null, 8, true, true, false, null, null)
			);
		}
	}
?>