<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-02-25 12:53:22                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoCreditRequestCreditorInvestorOffer extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'CreditRequestCreditorInvestorOffer', 8, true, true, false, null, null),
				'request' => LightMetaProperty::fill(new LightMetaProperty(), 'request', 'request_id', 'identifier', 'CreditRequestCreditor', null, true, false, false, 1, 3),
				'offer' => LightMetaProperty::fill(new LightMetaProperty(), 'offer', 'offer_id', 'identifier', 'InvestorOffer', null, true, false, false, 1, 3),
				'status' => LightMetaProperty::fill(new LightMetaProperty(), 'status', 'status_id', 'enumeration', 'CreditRequestCreditorInvestorOfferStatus', null, true, false, false, 1, 3),
				'createdTime' => LightMetaProperty::fill(new LightMetaProperty(), 'createdTime', 'created_time', 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'summ' => LightMetaProperty::fill(new LightMetaProperty(), 'summ', null, 'integer', null, 4, true, true, false, null, null),
				'period' => LightMetaProperty::fill(new LightMetaProperty(), 'period', null, 'integer', null, 4, false, true, false, null, null),
				'percents' => LightMetaProperty::fill(new LightMetaProperty(), 'percents', null, 'float', null, 4, true, true, false, null, null)
			);
		}
	}
?>