<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-02-25 01:26:34                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoCreditRequestCreditor extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'CreditRequestCreditor', 8, true, true, false, null, null),
				'createdTime' => LightMetaProperty::fill(new LightMetaProperty(), 'createdTime', 'created_time', 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'request' => LightMetaProperty::fill(new LightMetaProperty(), 'request', 'request_id', 'identifier', 'CreditRequest', null, true, false, false, 1, 3),
				'creditor' => LightMetaProperty::fill(new LightMetaProperty(), 'creditor', 'creditor_id', 'identifier', 'Creditor', null, true, false, false, 1, 3),
				'status' => LightMetaProperty::fill(new LightMetaProperty(), 'status', 'status_id', 'enumeration', 'CreditRequestCreditorStatus', null, true, false, false, 1, 3),
				'expired' => LightMetaProperty::fill(new LightMetaProperty(), 'expired', null, 'timestamp', 'Timestamp', null, false, true, false, null, null),
				'investSumm' => LightMetaProperty::fill(new LightMetaProperty(), 'investSumm', 'invest_summ', 'integer', null, 8, false, true, false, null, null),
				'investPeriod' => LightMetaProperty::fill(new LightMetaProperty(), 'investPeriod', 'invest_period', 'integer', null, 4, false, true, false, null, null),
				'investPercents' => LightMetaProperty::fill(new LightMetaProperty(), 'investPercents', 'invest_percents', 'integer', null, 4, false, true, false, null, null),
				'investNotified' => LightMetaProperty::fill(new LightMetaProperty(), 'investNotified', 'invest_notified', 'timestamp', 'Timestamp', null, false, true, false, null, null),
				'offers' => LightMetaProperty::fill(new LightMetaProperty(), 'offers', 'offers_id', 'identifierList', 'CreditRequestCreditorOffer', null, false, false, false, 2, null)
			);
		}
	}
?>