<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-06-26 14:23:20                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoNews extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'News', 8, true, true, false, null, null),
				'sid' => LightMetaProperty::fill(new LightMetaProperty(), 'sid', null, 'string', null, 64, true, true, false, null, null),
				'title' => LightMetaProperty::fill(new LightMetaProperty(), 'title', null, 'string', null, 64, true, true, false, null, null),
				'createdDate' => LightMetaProperty::fill(new LightMetaProperty(), 'createdDate', 'created_date', 'date', 'Date', null, true, true, false, null, null),
				'description' => LightMetaProperty::fill(new LightMetaProperty(), 'description', null, 'string', null, 255, true, true, false, null, null),
				'text' => LightMetaProperty::fill(new LightMetaProperty(), 'text', null, 'string', null, null, true, true, false, null, null),
				'type' => LightMetaProperty::fill(new LightMetaProperty(), 'type', 'type_id', 'enumeration', 'NewsType', null, true, false, false, 1, null),
				'preview' => LightMetaProperty::fill(new LightMetaProperty(), 'preview', 'preview_id', 'enumeration', 'ImageType', null, false, false, false, 1, null)
			);
		}
	}
?>