<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2019-12-26 13:56:19                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoImageOwner extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'ImageOwner', 8, true, true, false, null, null),
				'images' => LightMetaProperty::fill(new LightMetaProperty(), 'images', 'images_id', 'identifierList', 'ImageBase', null, false, false, false, 2, null)
			);
		}
	}
?>