<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2019-12-29 11:45:37                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoConfirm extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Confirm', 8, true, true, false, null, null),
				'type' => LightMetaProperty::fill(new LightMetaProperty(), 'type', 'type_id', 'enumeration', 'ConfirmType', null, true, false, false, 1, null),
				'createdTime' => LightMetaProperty::fill(new LightMetaProperty(), 'createdTime', 'created_time', 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'expiredTime' => LightMetaProperty::fill(new LightMetaProperty(), 'expiredTime', 'expired_time', 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'user' => LightMetaProperty::fill(new LightMetaProperty(), 'user', 'user_id', 'identifier', 'User', null, false, false, false, 1, 3),
				'phone' => LightMetaProperty::fill(new LightMetaProperty(), 'phone', null, 'integer', null, 8, false, true, false, null, null),
				'code' => LightMetaProperty::fill(new LightMetaProperty(), 'code', null, 'string', null, 255, true, true, false, null, null),
				'try' => LightMetaProperty::fill(new LightMetaProperty(), 'try', null, 'integer', null, 4, true, true, false, null, null)
			);
		}
	}
?>