<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-05 16:26:49                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoActionLog extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'ActionLog', 8, true, true, false, null, null),
				'createdTime' => LightMetaProperty::fill(new LightMetaProperty(), 'createdTime', 'created_time', 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'user' => LightMetaProperty::fill(new LightMetaProperty(), 'user', 'user_id', 'identifier', 'User', null, true, false, false, 1, 3),
				'ip' => LightMetaProperty::fill(new LightMetaProperty(), 'ip', null, 'integer', null, 4, true, true, false, null, null),
				'sid' => LightMetaProperty::fill(new LightMetaProperty(), 'sid', null, 'string', null, 64, false, true, false, null, null),
				'action' => LightMetaProperty::fill(new LightMetaProperty(), 'action', null, 'string', null, 64, true, true, false, null, null),
				'objectName' => LightMetaProperty::fill(new LightMetaProperty(), 'objectName', 'object_name', 'string', null, 255, true, true, false, null, null),
				'objectId' => LightMetaProperty::fill(new LightMetaProperty(), 'objectId', 'object_id', 'integer', null, 4, true, true, false, null, null)
			);
		}
	}
?>