<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2019-12-29 02:30:53                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoUser extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'User', 8, true, true, false, null, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 255, false, true, false, null, null),
				'createdTime' => LightMetaProperty::fill(new LightMetaProperty(), 'createdTime', 'created_time', 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'email' => LightMetaProperty::fill(new LightMetaProperty(), 'email', null, 'string', null, 255, true, true, false, null, null),
				'password' => LightMetaProperty::fill(new LightMetaProperty(), 'password', null, 'string', null, 255, true, true, false, null, null),
				'phone' => LightMetaProperty::fill(new LightMetaProperty(), 'phone', null, 'integer', null, 8, true, true, false, null, null),
				'active' => LightMetaProperty::fill(new LightMetaProperty(), 'active', null, 'boolean', null, null, true, true, false, null, null),
				'ban' => LightMetaProperty::fill(new LightMetaProperty(), 'ban', null, 'boolean', null, null, true, true, false, null, null),
				'banExpire' => LightMetaProperty::fill(new LightMetaProperty(), 'banExpire', 'ban_expire', 'timestamp', 'Timestamp', null, false, true, false, null, null),
				'banComment' => LightMetaProperty::fill(new LightMetaProperty(), 'banComment', 'ban_comment', 'string', null, 255, false, true, false, null, null)
			);
		}
	}
?>