<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-05 15:18:32                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoAclRightEdited extends IdentifiableObject
	{
		protected $name = null;
		protected $aclAction = null;
		protected $aclActionId = null;
		protected $context = null;
		protected $contextId = null;
		protected $sectionId = null;
		protected $sectionType = null;
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return AclRightEdited
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		/**
		 * @return AclAction
		**/
		public function getAclAction()
		{
			if (!$this->aclAction && $this->aclActionId) {
				$this->aclAction = AclAction::dao()->getById($this->aclActionId);
			}
			
			return $this->aclAction;
		}
		
		public function getAclActionId()
		{
			return $this->aclAction
				? $this->aclAction->getId()
				: $this->aclActionId;
		}
		
		/**
		 * @return AclRightEdited
		**/
		public function setAclAction(AclAction $aclAction)
		{
			$this->aclAction = $aclAction;
			$this->aclActionId = $aclAction ? $aclAction->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return AclRightEdited
		**/
		public function setAclActionId($id)
		{
			$this->aclAction = null;
			$this->aclActionId = $id;
			
			return $this;
		}
		
		/**
		 * @return AclRightEdited
		**/
		public function dropAclAction()
		{
			$this->aclAction = null;
			$this->aclActionId = null;
			
			return $this;
		}
		
		/**
		 * @return AclContext
		**/
		public function getContext()
		{
			if (!$this->context && $this->contextId) {
				$this->context = AclContext::dao()->getById($this->contextId);
			}
			
			return $this->context;
		}
		
		public function getContextId()
		{
			return $this->context
				? $this->context->getId()
				: $this->contextId;
		}
		
		/**
		 * @return AclRightEdited
		**/
		public function setContext(AclContext $context)
		{
			$this->context = $context;
			$this->contextId = $context ? $context->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return AclRightEdited
		**/
		public function setContextId($id)
		{
			$this->context = null;
			$this->contextId = $id;
			
			return $this;
		}
		
		/**
		 * @return AclRightEdited
		**/
		public function dropContext()
		{
			$this->context = null;
			$this->contextId = null;
			
			return $this;
		}
		
		public function getSectionId()
		{
			return $this->sectionId;
		}
		
		/**
		 * @return AclRightEdited
		**/
		public function setSectionId($sectionId)
		{
			$this->sectionId = $sectionId;
			
			return $this;
		}
		
		public function getSectionType()
		{
			return $this->sectionType;
		}
		
		/**
		 * @return AclRightEdited
		**/
		public function setSectionType($sectionType)
		{
			$this->sectionType = $sectionType;
			
			return $this;
		}
	}
?>