<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-05 14:55:03                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoAclRight extends NamedObject
	{
		protected $action = null;
		protected $actionId = null;
		protected $context = null;
		protected $contextId = null;
		protected $sectionId = null;
		protected $sectionType = null;
		
		/**
		 * @return AclAction
		**/
		public function getAction()
		{
			if (!$this->action && $this->actionId) {
				$this->action = AclAction::dao()->getById($this->actionId);
			}
			
			return $this->action;
		}
		
		public function getActionId()
		{
			return $this->action
				? $this->action->getId()
				: $this->actionId;
		}
		
		/**
		 * @return AclRight
		**/
		public function setAction(AclAction $action)
		{
			$this->action = $action;
			$this->actionId = $action ? $action->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return AclRight
		**/
		public function setActionId($id)
		{
			$this->action = null;
			$this->actionId = $id;
			
			return $this;
		}
		
		/**
		 * @return AclRight
		**/
		public function dropAction()
		{
			$this->action = null;
			$this->actionId = null;
			
			return $this;
		}
		
		/**
		 * @return AclContext
		**/
		public function getContext()
		{
			if (!$this->context && $this->contextId) {
				$this->context = AclContext::dao()->getById($this->contextId);
			}
			
			return $this->context;
		}
		
		public function getContextId()
		{
			return $this->context
				? $this->context->getId()
				: $this->contextId;
		}
		
		/**
		 * @return AclRight
		**/
		public function setContext(AclContext $context)
		{
			$this->context = $context;
			$this->contextId = $context ? $context->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return AclRight
		**/
		public function setContextId($id)
		{
			$this->context = null;
			$this->contextId = $id;
			
			return $this;
		}
		
		/**
		 * @return AclRight
		**/
		public function dropContext()
		{
			$this->context = null;
			$this->contextId = null;
			
			return $this;
		}
		
		public function getSectionId()
		{
			return $this->sectionId;
		}
		
		/**
		 * @return AclRight
		**/
		public function setSectionId($sectionId)
		{
			$this->sectionId = $sectionId;
			
			return $this;
		}
		
		public function getSectionType()
		{
			return $this->sectionType;
		}
		
		/**
		 * @return AclRight
		**/
		public function setSectionType($sectionType)
		{
			$this->sectionType = $sectionType;
			
			return $this;
		}
	}
?>