<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2019-12-29 11:45:37                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoConfirm extends IdentifiableObject implements Created
	{
		protected $type = null;
		protected $createdTime = null;
		protected $expiredTime = null;
		protected $user = null;
		protected $userId = null;
		protected $phone = null;
		protected $code = null;
		protected $try = 0;
		
		/**
		 * @return ConfirmType
		**/
		public function getType()
		{
			return $this->type;
		}
		
		/**
		 * @return Confirm
		**/
		public function setType(ConfirmType $type)
		{
			$this->type = $type;
			
			return $this;
		}
		
		/**
		 * @return Confirm
		**/
		public function dropType()
		{
			$this->type = null;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getCreatedTime()
		{
			return $this->createdTime;
		}
		
		/**
		 * @return Confirm
		**/
		public function setCreatedTime(Timestamp $createdTime)
		{
			$this->createdTime = $createdTime;
			
			return $this;
		}
		
		/**
		 * @return Confirm
		**/
		public function dropCreatedTime()
		{
			$this->createdTime = null;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getExpiredTime()
		{
			return $this->expiredTime;
		}
		
		/**
		 * @return Confirm
		**/
		public function setExpiredTime(Timestamp $expiredTime)
		{
			$this->expiredTime = $expiredTime;
			
			return $this;
		}
		
		/**
		 * @return Confirm
		**/
		public function dropExpiredTime()
		{
			$this->expiredTime = null;
			
			return $this;
		}
		
		/**
		 * @return User
		**/
		public function getUser()
		{
			if (!$this->user && $this->userId) {
				$this->user = User::dao()->getById($this->userId);
			}
			
			return $this->user;
		}
		
		public function getUserId()
		{
			return $this->user
				? $this->user->getId()
				: $this->userId;
		}
		
		/**
		 * @return Confirm
		**/
		public function setUser(User $user = null)
		{
			$this->user = $user;
			$this->userId = $user ? $user->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return Confirm
		**/
		public function setUserId($id = null)
		{
			$this->user = null;
			$this->userId = $id;
			
			return $this;
		}
		
		/**
		 * @return Confirm
		**/
		public function dropUser()
		{
			$this->user = null;
			$this->userId = null;
			
			return $this;
		}
		
		public function getPhone()
		{
			return $this->phone;
		}
		
		/**
		 * @return Confirm
		**/
		public function setPhone($phone)
		{
			$this->phone = $phone;
			
			return $this;
		}
		
		public function getCode()
		{
			return $this->code;
		}
		
		/**
		 * @return Confirm
		**/
		public function setCode($code)
		{
			$this->code = $code;
			
			return $this;
		}
		
		public function getTry()
		{
			return $this->try;
		}
		
		/**
		 * @return Confirm
		**/
		public function setTry($try)
		{
			$this->try = $try;
			
			return $this;
		}
	}
?>