<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-04 14:57:08                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoAclAction extends NamedObject
	{
		protected $action = null;
		
		public function getAction()
		{
			return $this->action;
		}
		
		/**
		 * @return AclAction
		**/
		public function setAction($action)
		{
			$this->action = $action;
			
			return $this;
		}
	}
?>