<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-02-08 14:59:33                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCreditRequestImage extends ImageBase implements ImageUniqueFileName
	{
		protected $owner = null;
		protected $ownerId = null;
		protected $fileName = null;
		
		/**
		 * @return CreditRequest
		**/
		public function getOwner()
		{
			if (!$this->owner && $this->ownerId) {
				$this->owner = CreditRequest::dao()->getById($this->ownerId);
			}
			
			return $this->owner;
		}
		
		public function getOwnerId()
		{
			return $this->owner
				? $this->owner->getId()
				: $this->ownerId;
		}
		
		/**
		 * @return CreditRequestImage
		**/
		public function setOwner(CreditRequest $owner = null)
		{
			$this->owner = $owner;
			$this->ownerId = $owner ? $owner->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return CreditRequestImage
		**/
		public function setOwnerId($id = null)
		{
			$this->owner = null;
			$this->ownerId = $id;
			
			return $this;
		}
		
		/**
		 * @return CreditRequestImage
		**/
		public function dropOwner()
		{
			$this->owner = null;
			$this->ownerId = null;
			
			return $this;
		}
		
		public function getFileName()
		{
			return $this->fileName;
		}
		
		/**
		 * @return CreditRequestImage
		**/
		public function setFileName($fileName)
		{
			$this->fileName = $fileName;
			
			return $this;
		}
	}
?>