<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-02-25 12:53:22                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCreditRequestCreditorInvestorOffer extends IdentifiableObject implements Created, SecurityObject
	{
		protected $request = null;
		protected $requestId = null;
		protected $offer = null;
		protected $offerId = null;
		protected $status = null;
		protected $statusId = null;
		protected $createdTime = null;
		protected $summ = null;
		protected $period = null;
		protected $percents = null;
		
		/**
		 * @return CreditRequestCreditor
		**/
		public function getRequest()
		{
			if (!$this->request && $this->requestId) {
				$this->request = CreditRequestCreditor::dao()->getById($this->requestId);
			}
			
			return $this->request;
		}
		
		public function getRequestId()
		{
			return $this->request
				? $this->request->getId()
				: $this->requestId;
		}
		
		/**
		 * @return CreditRequestCreditorInvestorOffer
		**/
		public function setRequest(CreditRequestCreditor $request)
		{
			$this->request = $request;
			$this->requestId = $request ? $request->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return CreditRequestCreditorInvestorOffer
		**/
		public function setRequestId($id)
		{
			$this->request = null;
			$this->requestId = $id;
			
			return $this;
		}
		
		/**
		 * @return CreditRequestCreditorInvestorOffer
		**/
		public function dropRequest()
		{
			$this->request = null;
			$this->requestId = null;
			
			return $this;
		}
		
		/**
		 * @return InvestorOffer
		**/
		public function getOffer()
		{
			if (!$this->offer && $this->offerId) {
				$this->offer = InvestorOffer::dao()->getById($this->offerId);
			}
			
			return $this->offer;
		}
		
		public function getOfferId()
		{
			return $this->offer
				? $this->offer->getId()
				: $this->offerId;
		}
		
		/**
		 * @return CreditRequestCreditorInvestorOffer
		**/
		public function setOffer(InvestorOffer $offer)
		{
			$this->offer = $offer;
			$this->offerId = $offer ? $offer->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return CreditRequestCreditorInvestorOffer
		**/
		public function setOfferId($id)
		{
			$this->offer = null;
			$this->offerId = $id;
			
			return $this;
		}
		
		/**
		 * @return CreditRequestCreditorInvestorOffer
		**/
		public function dropOffer()
		{
			$this->offer = null;
			$this->offerId = null;
			
			return $this;
		}
		
		/**
		 * @return CreditRequestCreditorInvestorOfferStatus
		**/
		public function getStatus()
		{
			if (!$this->status && $this->statusId) {
				$this->status = new CreditRequestCreditorInvestorOfferStatus($this->statusId);
			}
			
			return $this->status;
		}
		
		public function getStatusId()
		{
			return $this->status
				? $this->status->getId()
				: $this->statusId;
		}
		
		/**
		 * @return CreditRequestCreditorInvestorOffer
		**/
		public function setStatus(CreditRequestCreditorInvestorOfferStatus $status)
		{
			$this->status = $status;
			$this->statusId = $status ? $status->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return CreditRequestCreditorInvestorOffer
		**/
		public function setStatusId($id)
		{
			$this->status = null;
			$this->statusId = $id;
			
			return $this;
		}
		
		/**
		 * @return CreditRequestCreditorInvestorOffer
		**/
		public function dropStatus()
		{
			$this->status = null;
			$this->statusId = null;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getCreatedTime()
		{
			return $this->createdTime;
		}
		
		/**
		 * @return CreditRequestCreditorInvestorOffer
		**/
		public function setCreatedTime(Timestamp $createdTime)
		{
			$this->createdTime = $createdTime;
			
			return $this;
		}
		
		/**
		 * @return CreditRequestCreditorInvestorOffer
		**/
		public function dropCreatedTime()
		{
			$this->createdTime = null;
			
			return $this;
		}
		
		public function getSumm()
		{
			return $this->summ;
		}
		
		/**
		 * @return CreditRequestCreditorInvestorOffer
		**/
		public function setSumm($summ)
		{
			$this->summ = $summ;
			
			return $this;
		}
		
		public function getPeriod()
		{
			return $this->period;
		}
		
		/**
		 * @return CreditRequestCreditorInvestorOffer
		**/
		public function setPeriod($period)
		{
			$this->period = $period;
			
			return $this;
		}
		
		public function getPercents()
		{
			return $this->percents;
		}
		
		/**
		 * @return CreditRequestCreditorInvestorOffer
		**/
		public function setPercents($percents)
		{
			$this->percents = $percents;
			
			return $this;
		}
	}
?>