<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-08 18:33:13                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCreditorCategory extends IdentifiableObject
	{
		protected $creditor = null;
		protected $creditorId = null;
		protected $category = null;
		protected $categoryId = null;
		
		/**
		 * @return Creditor
		**/
		public function getCreditor()
		{
			if (!$this->creditor && $this->creditorId) {
				$this->creditor = Creditor::dao()->getById($this->creditorId);
			}
			
			return $this->creditor;
		}
		
		public function getCreditorId()
		{
			return $this->creditor
				? $this->creditor->getId()
				: $this->creditorId;
		}
		
		/**
		 * @return CreditorCategory
		**/
		public function setCreditor(Creditor $creditor)
		{
			$this->creditor = $creditor;
			$this->creditorId = $creditor ? $creditor->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return CreditorCategory
		**/
		public function setCreditorId($id)
		{
			$this->creditor = null;
			$this->creditorId = $id;
			
			return $this;
		}
		
		/**
		 * @return CreditorCategory
		**/
		public function dropCreditor()
		{
			$this->creditor = null;
			$this->creditorId = null;
			
			return $this;
		}
		
		/**
		 * @return Category
		**/
		public function getCategory()
		{
			if (!$this->category && $this->categoryId) {
				$this->category = Category::dao()->getById($this->categoryId);
			}
			
			return $this->category;
		}
		
		public function getCategoryId()
		{
			return $this->category
				? $this->category->getId()
				: $this->categoryId;
		}
		
		/**
		 * @return CreditorCategory
		**/
		public function setCategory(Category $category)
		{
			$this->category = $category;
			$this->categoryId = $category ? $category->getId() : null;
			
			return $this;
		}
		
		/**
		 * @return CreditorCategory
		**/
		public function setCategoryId($id)
		{
			$this->category = null;
			$this->categoryId = $id;
			
			return $this;
		}
		
		/**
		 * @return CreditorCategory
		**/
		public function dropCategory()
		{
			$this->category = null;
			$this->categoryId = null;
			
			return $this;
		}
	}
?>