<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-03-15 16:53:42                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCategory extends NamedObject implements Sortable
	{
		protected $sort = null;
		protected $text = null;
		protected $pledge = true;
		
		public function getSort()
		{
			return $this->sort;
		}
		
		/**
		 * @return Category
		**/
		public function setSort($sort)
		{
			$this->sort = $sort;
			
			return $this;
		}
		
		public function getText()
		{
			return $this->text;
		}
		
		/**
		 * @return Category
		**/
		public function setText($text)
		{
			$this->text = $text;
			
			return $this;
		}
		
		public function getPledge()
		{
			return $this->pledge;
		}
		
		public function isPledge()
		{
			return $this->pledge;
		}
		
		/**
		 * @return Category
		**/
		public function setPledge($pledge = false)
		{
			$this->pledge = ($pledge === true);
			
			return $this;
		}
	}
?>