<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2019-12-26 19:15:46                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoUser extends NamedObject implements Created
	{
		protected $createdTime = null;
		protected $email = null;
		protected $password = null;
		protected $phone = null;
		protected $active = false;
		protected $ban = false;
		protected $banExpire = null;
		protected $banComment = null;
		
		/**
		 * @return Timestamp
		**/
		public function getCreatedTime()
		{
			return $this->createdTime;
		}
		
		/**
		 * @return User
		**/
		public function setCreatedTime(Timestamp $createdTime)
		{
			$this->createdTime = $createdTime;
			
			return $this;
		}
		
		/**
		 * @return User
		**/
		public function dropCreatedTime()
		{
			$this->createdTime = null;
			
			return $this;
		}
		
		public function getEmail()
		{
			return $this->email;
		}
		
		/**
		 * @return User
		**/
		public function setEmail($email)
		{
			$this->email = $email;
			
			return $this;
		}
		
		public function getPassword()
		{
			return $this->password;
		}
		
		/**
		 * @return User
		**/
		public function setPassword($password)
		{
			$this->password = $password;
			
			return $this;
		}
		
		public function getPhone()
		{
			return $this->phone;
		}
		
		/**
		 * @return User
		**/
		public function setPhone($phone)
		{
			$this->phone = $phone;
			
			return $this;
		}
		
		public function getActive()
		{
			return $this->active;
		}
		
		public function isActive()
		{
			return $this->active;
		}
		
		/**
		 * @return User
		**/
		public function setActive($active = false)
		{
			$this->active = ($active === true);
			
			return $this;
		}
		
		public function getBan()
		{
			return $this->ban;
		}
		
		public function isBan()
		{
			return $this->ban;
		}
		
		/**
		 * @return User
		**/
		public function setBan($ban = false)
		{
			$this->ban = ($ban === true);
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getBanExpire()
		{
			return $this->banExpire;
		}
		
		/**
		 * @return User
		**/
		public function setBanExpire(Timestamp $banExpire = null)
		{
			$this->banExpire = $banExpire;
			
			return $this;
		}
		
		/**
		 * @return User
		**/
		public function dropBanExpire()
		{
			$this->banExpire = null;
			
			return $this;
		}
		
		public function getBanComment()
		{
			return $this->banComment;
		}
		
		/**
		 * @return User
		**/
		public function setBanComment($banComment)
		{
			$this->banComment = $banComment;
			
			return $this;
		}
	}
?>