<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-04 15:27:14                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoAclActionEdited extends IdentifiableObject
	{
		protected $name = null;
		protected $aclAction = null;
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return AclActionEdited
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getAclAction()
		{
			return $this->aclAction;
		}
		
		/**
		 * @return AclActionEdited
		**/
		public function setAclAction($aclAction)
		{
			$this->aclAction = $aclAction;
			
			return $this;
		}
	}
?>