<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-05 14:55:03                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoAclGroup extends NamedObject
	{
		protected $rights = null;
		
		/**
		 * @return AclGroupRightsDAO
		**/
		public function getRights($lazy = false)
		{
			if (!$this->rights || ($this->rights->isLazy() != $lazy)) {
				$this->rights = new AclGroupRightsDAO($this, $lazy);
			}
			
			return $this->rights;
		}
		
		/**
		 * @return AclGroup
		**/
		public function fillRights($collection, $lazy = false)
		{
			$this->rights = new AclGroupRightsDAO($this, $lazy);
			
			if (!$this->id) {
				throw new WrongStateException(
					'i do not know which object i belong to'
				);
			}
			
			$this->rights->mergeList($collection);
			
			return $this;
		}
	}
?>