<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-04 15:27:14                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class AclActionEdited extends AutoAclActionEdited implements Prototyped, DAOConnected
	{
		/**
		 * @return AclActionEdited
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return AclActionEditedDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('AclActionEditedDAO');
		}
		
		/**
		 * @return ProtoAclActionEdited
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoAclActionEdited');
		}
		
		// your brilliant stuff goes here
	}
?>