<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-04 14:57:08                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class AclAction extends AutoAclAction implements Prototyped, DAOConnected
	{
            const ACTION_ALLOWED = "/^[a-z\d][a-z-\d]{0,30}[a-z\d]$/isu";

            const ADD_ACTION = 'add';
            const EDIT_ACTION = 'save';
            const VIEW_ACTION = 'view';
            const DELETE_ACTION = 'delete';
            const RESTORE_ACTION = 'restore';
            const PUBLISH_ACTION = 'publish';
            const REJECT_ACTION         = 'reject';
            const CANCEL_ACTION         = 'cancel';
            const ACCEPT_ACTION         = 'accept';

            protected static $emptyActionList = array(
                self::ADD_ACTION => self::ADD_ACTION,
                self::VIEW_ACTION => self::VIEW_ACTION
            );
            
            /**
             * @return AclAction
            **/
            public static function create()
            {
                    return new self;
            }

            /**
             * @return AclActionDAO
            **/
            public static function dao()
            {
                    return Singleton::getInstance('AclActionDAO');
            }

            /**
             * @return ProtoAclAction
            **/
            public static function proto()
            {
                    return Singleton::getInstance('ProtoAclAction');
            }

            /**
             * Проверка на необходимость объекта для действия
             *
             * @param string $action
             * @return boolean
             */
            public static function isEmptyAction($action)
            {
                return isset(self::$emptyActionList[$action]);
            }

            public function checkPermissions($action)
            {
                return true;
            }
	}
?>