<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-04 15:34:44                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class AclContext extends AutoAclContext implements Prototyped, DAOConnected
	{
            const ACL_ID                            = 1; // права на сайте    
            
            /**
             * @return AclContext
            **/
            public static function create()
            {
                    return new self;
            }

            /**
             * @return AclContextDAO
            **/
            public static function dao()
            {
                    return Singleton::getInstance('AclContextDAO');
            }

            /**
             * @return ProtoAclContext
            **/
            public static function proto()
            {
                    return Singleton::getInstance('ProtoAclContext');
            }

            // your brilliant stuff goes here
	}
?>