<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-05 15:18:32                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class AclRightEdited extends AutoAclRightEdited implements Prototyped, DAOConnected
	{
		/**
		 * @return AclRightEdited
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return AclRightEditedDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('AclRightEditedDAO');
		}
		
		/**
		 * @return ProtoAclRightEdited
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoAclRightEdited');
		}
		
		// your brilliant stuff goes here
	}
?>