<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2019-12-29 02:09:44                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class Confirm extends AutoConfirm implements Prototyped, DAOConnected
	{
		/**
		 * @return Confirm
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return ConfirmDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('ConfirmDAO');
		}
		
		/**
		 * @return ProtoConfirm
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoConfirm');
		}
		
		// your brilliant stuff goes here
	}
?>