<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-08 18:33:13                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class CreditorCategory extends AutoCreditorCategory implements Prototyped, DAOConnected
	{
		/**
		 * @return CreditorCategory
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return CreditorCategoryDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('CreditorCategoryDAO');
		}
		
		/**
		 * @return ProtoCreditorCategory
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoCreditorCategory');
		}
		
		// your brilliant stuff goes here
	}
?>