<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-02-08 01:10:03                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class CreditRequestImage extends AutoCreditRequestImage implements Prototyped, DAOConnected
	{
		/**
		 * @return CreditRequestImage
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return CreditRequestImageDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('CreditRequestImageDAO');
		}
		
		/**
		 * @return ProtoCreditRequestImage
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoCreditRequestImage');
		}
		
		// your brilliant stuff goes here
	}
?>