<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-02-17 01:39:32                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class CreditRequestCreditorOffer extends AutoCreditRequestCreditorOffer implements Prototyped, DAOConnected
	{
		/**
		 * @return CreditRequestCreditorOffer
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return CreditRequestCreditorOfferDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('CreditRequestCreditorOfferDAO');
		}
		
		/**
		 * @return ProtoCreditRequestCreditorOffer
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoCreditRequestCreditorOffer');
		}
		
		public function checkPermissions($label)
                {
                    return 
                        //($label == AclAction::EDIT_ACTION && $this->getStatus()->getId() == CreditRequestStatus::TYPE_INCOME && SecurityManager::isAllowedAction(AclAction::PUBLISH_ACTION, AclContext::CREDIT_REQUEST_ID)) ||
                        //($label == AclAction::VIEW_ACTION && ((SecurityManager::isAuth() && $this->getUser()->getId() == SecurityManager::getUser()->getId() && !$this->isDeleted()) || SecurityManager::isAllowedAction($label, AclContext::CREDIT_REQUEST_ID))) ||
                        /**
                         * Удалить можно только в статусе поступило и только в статусе запроса рассматривается
                         */
                        ($label == AclAction::DELETE_ACTION && $this->getStatus()->getId() == CreditRequestCreditorOfferStatus::TYPE_INCOME && $this->getRequest()->getStatus()->getId() == CreditRequestCreditorStatus::TYPE_CONCIDERED && ((SecurityManager::isAuth() && $this->getRequest()->getCreditor()->getUser()->getId() == SecurityManager::getUser()->getId()) || SecurityManager::isAllowedAction($label, AclContext::CREDIT_REQUEST_CREDITOR_OFFER))) ||
                        /**
                         * Отклонять:
                         * - может отклонить заемщик при соотетствующем статусе запроса к компании - рассматривается и статусе предложения поступил
                         */
                        (
                            $label == AclAction::CANCEL_ACTION && SecurityManager::isAuth() &&
                            
                            !$this->getRequest()->getRequest()->isDeleted() &&
                            $this->getRequest()->getRequest()->getUser()->getId() == SecurityManager::getUser()->getId() &&
                            $this->getStatus()->getId() == CreditRequestCreditorOfferStatus::TYPE_INCOME && 
                            $this->getRequest()->getStatus()->getId() == CreditRequestCreditorStatus::TYPE_CONCIDERED
                        ) ||
                        /**
                         * Принять предложение:
                         * - может только заемщик у предложения в статусе поступило и если в заявке нет других принятых предложений
                         */
                        (
                            $label == AclAction::ACCEPT_ACTION && SecurityManager::isAuth() &&
                            
                            !$this->getRequest()->getRequest()->isDeleted() &&
                            !$this->getRequest()->getRequest()->hasAcceptedOffers() &&
                            $this->getRequest()->getRequest()->getUser()->getId() == SecurityManager::getUser()->getId() &&
                            $this->getStatus()->getId() == CreditRequestCreditorOfferStatus::TYPE_INCOME && 
                            $this->getRequest()->getStatus()->getId() == CreditRequestCreditorStatus::TYPE_CONCIDERED
                        ) ||
                        //($label == AclAction::RESTORE_ACTION && $this->isDeleted() && SecurityManager::isAllowedAction($label, AclContext::CREDIT_REQUEST_ID)) ||
                        (
                            //$label != AclAction::EDIT_ACTION &&
                            //$label != AclAction::VIEW_ACTION &&
                            $label != AclAction::DELETE_ACTION &&
                            $label != AclAction::CANCEL_ACTION &&
                            $label != AclAction::ACCEPT_ACTION
                            //$label != AclAction::RESTORE_ACTION
                        );
                }
	}
?>