<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-12 23:19:36                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class CreditRequest extends AutoCreditRequest implements Prototyped, DAOConnected
	{
		/**
		 * @return CreditRequest
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return CreditRequestDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('CreditRequestDAO');
		}
		
		/**
		 * @return ProtoCreditRequest
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoCreditRequest');
		}
		
		public function checkPermissions($label)
                {                    
                    return 
                        ($label == AclAction::VIEW_ACTION && ((SecurityManager::isAuth() && $this->getUser()->getId() == SecurityManager::getUser()->getId() && !$this->isDeleted()) || SecurityManager::isAllowedAction($label, AclContext::CREDIT_REQUEST_ID))) ||
                        ($label == AclAction::DELETE_ACTION && !$this->isDeleted() && ((SecurityManager::isAuth() && $this->getUser()->getId() == SecurityManager::getUser()->getId()) || SecurityManager::isAllowedAction($label, AclContext::CREDIT_REQUEST_ID))) ||
                        ($label == AclAction::RESTORE_ACTION && $this->isDeleted() && SecurityManager::isAllowedAction($label, AclContext::CREDIT_REQUEST_ID)) ||
                        (
                            $label != AclAction::VIEW_ACTION &&
                            $label != AclAction::DELETE_ACTION &&
                            $label != AclAction::RESTORE_ACTION
                        );
                }
	}
?>