<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2019-12-26 13:56:19                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	abstract class ImageOwner extends AutoImageOwner implements Prototyped
	{
		// your brilliant stuff goes here
	}
?>