<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-06-23 13:22:32                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class News extends AutoNews implements Prototyped, DAOConnected
	{
		/**
		 * @return News
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return NewsDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('NewsDAO');
		}
		
		/**
		 * @return ProtoNews
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoNews');
		}
		
		public function getPreviewFile($type = PictureUtils::PREVIEW_IMAGE_TYPE_SMALL)
                {
                    if ($this->getPreview() instanceof ImageType) {
                        return $this->getId() . PictureUtils::getPreviewFilePostfixByType($type) . '.' . $this->getPreview()->getExtension();
                    } else {
                        return '';
                    }
                }

                public function getPreviewPath($type = PictureUtils::PREVIEW_IMAGE_TYPE_SMALL)
                {
                    return PictureUtils::getPreviewPathByObject($this) . $this->getPreviewFile($type);
                }

                public function getPreviewUrl($type = PictureUtils::PREVIEW_IMAGE_TYPE_SMALL)
                {
                    return PictureUtils::getPreviewUrlByObject($this) . $this->getPreviewFile($type);
                }
	}
?>