<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-06-23 13:22:32                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class News extends AutoNews implements Prototyped, DAOConnected
	{
		/**
		 * @return News
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return NewsDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('NewsDAO');
		}
		
		/**
		 * @return ProtoNews
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoNews');
		}
		
		// your brilliant stuff goes here
	}
?>