<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2020-01-04 22:05:24                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class SecurityLog extends AutoSecurityLog implements Prototyped, DAOConnected
	{
		/**
		 * @return SecurityLog
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return SecurityLogDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('SecurityLogDAO');
		}
		
		/**
		 * @return ProtoSecurityLog
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoSecurityLog');
		}
		
		public function getRealIp()
                {
                    return long2ip($this->getIp());
                }

                public function setRealIp($ip)
                {
                    return $this->setIp(ip2long($ip));
                }
	}
?>