<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2019-12-26 13:54:24                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class User extends AutoUser implements Prototyped, DAOConnected
	{
		/**
		 * @return User
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return UserDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('UserDAO');
		}
		
		/**
		 * @return ProtoUser
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoUser');
		}
		
		// your brilliant stuff goes here
	}
?>